# for Linux
[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C",
  "link-arg=-fuse-ld=lld",
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]
linker = "clang"

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
